// Generated by data class generator
// DO NOT MODIFY BY HAND

part of 'builtin_converters_example.dart';

mixin _Task {
  abstract final String title;
  abstract final DateTime createdAt;
  abstract final DateTime? dueDate;
  abstract final Duration estimatedTime;
  abstract final Duration? actualTime;
  abstract final Priority priority;
  abstract final Priority? secondaryPriority;
  abstract final bool isCompleted;

  Task copyWith({
    String? title,
    DateTime? createdAt,
    DateTime? dueDate,
    Duration? estimatedTime,
    Duration? actualTime,
    Priority? priority,
    Priority? secondaryPriority,
    bool? isCompleted,
  }) {
    return Task(
      title: title ?? this.title,
      createdAt: createdAt ?? this.createdAt,
      dueDate: dueDate ?? this.dueDate,
      estimatedTime: estimatedTime ?? this.estimatedTime,
      actualTime: actualTime ?? this.actualTime,
      priority: priority ?? this.priority,
      secondaryPriority: secondaryPriority ?? this.secondaryPriority,
      isCompleted: isCompleted ?? this.isCompleted,
    );
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    if (other is! Task) return false;

    if (title != other.title) {
      return false;
    }
    if (createdAt != other.createdAt) {
      return false;
    }
    if (dueDate != other.dueDate) {
      return false;
    }
    if (estimatedTime != other.estimatedTime) {
      return false;
    }
    if (actualTime != other.actualTime) {
      return false;
    }
    if (priority != other.priority) {
      return false;
    }
    if (secondaryPriority != other.secondaryPriority) {
      return false;
    }
    if (isCompleted != other.isCompleted) {
      return false;
    }
    return true;
  }

  @override
  int get hashCode {
    return Object.hashAll([
      title,
      createdAt,
      dueDate,
      estimatedTime,
      actualTime,
      priority,
      secondaryPriority,
      isCompleted,
    ]);
  }

  @override
  String toString() {
    return 'Task(title: $title, createdAt: $createdAt, dueDate: $dueDate, estimatedTime: $estimatedTime, actualTime: $actualTime, priority: $priority, secondaryPriority: $secondaryPriority, isCompleted: $isCompleted)';
  }

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    map['title'] = title;
    map['createdAt'] = const DateTimeConverter().toJson(createdAt);
    if (dueDate != null) {
      map['dueDate'] = dueDate != null
          ? const DateTimeMillisecondsConverter().toJson(dueDate!)
          : null;
    }
    map['estimatedTime'] = const DurationConverter().toJson(estimatedTime);
    if (actualTime != null) {
      map['actualTime'] = actualTime != null
          ? const DurationMillisecondsConverter().toJson(actualTime!)
          : null;
    }
    map['priority'] = const EnumConverter(Priority.values).toJson(priority);
    if (secondaryPriority != null) {
      map['secondaryPriority'] = secondaryPriority != null
          ? const EnumIndexConverter(Priority.values).toJson(secondaryPriority!)
          : null;
    }
    map['isCompleted'] = isCompleted;
    return map;
  }

  static Task fromJson(Map<String, dynamic> map) {
    return Task(
      title: (map['title'])?.toString() ?? "",
      createdAt: map['createdAt'] != null
          ? const DateTimeConverter().fromJson(map['createdAt'])
          : throw ArgumentError('Required field createdAt is missing'),
      dueDate: map['dueDate'] != null
          ? const DateTimeMillisecondsConverter().fromJson(map['dueDate'])
          : null,
      estimatedTime: map['estimatedTime'] != null
          ? const DurationConverter().fromJson(map['estimatedTime'])
          : throw ArgumentError('Required field estimatedTime is missing'),
      actualTime: map['actualTime'] != null
          ? const DurationMillisecondsConverter().fromJson(map['actualTime'])
          : null,
      priority: map['priority'] != null
          ? const EnumConverter(Priority.values).fromJson(map['priority'])
          : throw ArgumentError('Required field priority is missing'),
      secondaryPriority: map['secondaryPriority'] != null
          ? const EnumIndexConverter(Priority.values)
              .fromJson(map['secondaryPriority'])
          : null,
      isCompleted: (map['isCompleted'] as bool?) ?? false,
    );
  }
}
