// Generated by data class generator
// DO NOT MODIFY BY HAND

part of 'alternate_names_test.model.dart';

mixin _AlternateNamesTest {
  abstract final String name;
  abstract final int age;
  abstract final String email;
  abstract final bool isActive;
  abstract final List<String> tags;

  AlternateNamesTest copyWith({
    String? name,
    int? age,
    String? email,
    bool? isActive,
    List<String>? tags,
  }) {
    return AlternateNamesTest(
      name: name ?? this.name,
      age: age ?? this.age,
      email: email ?? this.email,
      isActive: isActive ?? this.isActive,
      tags: tags ?? this.tags,
    );
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    if (other is! AlternateNamesTest) return false;

    if (name != other.name) {
      return false;
    }
    if (age != other.age) {
      return false;
    }
    if (email != other.email) {
      return false;
    }
    if (isActive != other.isActive) {
      return false;
    }
    if (!const DeepCollectionEquality().equals(tags, other.tags)) {
      return false;
    }
    return true;
  }

  @override
  int get hashCode {
    return Object.hashAll([
      name,
      age,
      email,
      isActive,
      const DeepCollectionEquality().hash(tags),
    ]);
  }

  @override
  String toString() {
    return 'AlternateNamesTest(name: $name, age: $age, email: $email, isActive: $isActive, tags: $tags)';
  }

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    map['name'] = name;
    map['user_age'] = age;
    map['email'] = email;
    map['is_active'] = isActive;
    map['tags'] = tags;
    return map;
  }

  static AlternateNamesTest fromJson(Map<String, dynamic> map) {
    return AlternateNamesTest(
      name: (map['name'])?.toString() ?? "",
      age: int.tryParse((map['user_age'] ?? map['age'] ?? map['years'] ?? '')
              .toString()) ??
          0,
      email:
          (map['email'] ?? map['email_address'] ?? map['mail'] ?? map['e_mail'])
                  ?.toString() ??
              "",
      isActive:
          (map['is_active'] ?? map['active'] ?? map['enabled'] as bool?) ??
              false,
      tags: ((map['tags'] as List<dynamic>?) ??
                  (map['tags_list'] as List<dynamic>?) ??
                  (map['labels'] as List<dynamic>?))
              ?.map((e) => e.toString())
              .toList() ??
          const [],
    );
  }
}
