// Generated by data class generator
// DO NOT MODIFY BY HAND

part of 'auto_fromjson_test.model.dart';

mixin _AutoFromJsonTest {
  abstract final String name;
  abstract final int age;
  abstract final bool isActive;

  AutoFromJsonTest copyWith({
    String? name,
    int? age,
    bool? isActive,
  }) {
    return AutoFromJsonTest(
      name: name ?? this.name,
      age: age ?? this.age,
      isActive: isActive ?? this.isActive,
    );
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    if (other is! AutoFromJsonTest) return false;

    if (name != other.name) {
      return false;
    }
    if (age != other.age) {
      return false;
    }
    if (isActive != other.isActive) {
      return false;
    }
    return true;
  }

  @override
  int get hashCode {
    return Object.hashAll([
      name,
      age,
      isActive,
    ]);
  }
  @override
  String toString() {
    return 'AutoFromJsonTest(name: $name, age: $age, isActive: $isActive)';
  }


  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    map['name'] = name;
    map['age'] = age;
    map['isActive'] = isActive;
    return map;
  }

  static AutoFromJsonTest fromJson(Map<String, dynamic> map) {
    return AutoFromJsonTest(
      name: (map['name'])?.toString() ?? "",
      age: int.tryParse((map['age'] ?? '').toString()) ?? 0,
      isActive: (map['isActive'] as bool?) ?? true,
    );
  }
}

