// Generated by data class generator
// DO NOT MODIFY BY HAND

part of 'auto_fromjson_test.model.dart';

mixin _AutoFromJsonTest {
  abstract final String name;
  abstract final int age;
  abstract final bool isActive;

  _AutoFromJsonTestCopyWith get copyWith =>
      _AutoFromJsonTestCopyWith._(this as AutoFromJsonTest);

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    if (other is! AutoFromJsonTest) return false;

    if (name != other.name) {
      return false;
    }
    if (age != other.age) {
      return false;
    }
    if (isActive != other.isActive) {
      return false;
    }
    return true;
  }

  @override
  int get hashCode {
    return Object.hashAll([
      name,
      age,
      isActive,
    ]);
  }

  @override
  String toString() {
    return 'AutoFromJsonTest(name: $name, age: $age, isActive: $isActive)';
  }

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    map['name'] = name;
    map['age'] = age;
    map['isActive'] = isActive;
    return map;
  }

  static AutoFromJsonTest fromJson(Map<String, dynamic> map) {
    return AutoFromJsonTest(
      name: SafeCasteUtil.safeCast<String>(map['name']) ?? "",
      age: SafeCasteUtil.safeCast<int>(map['age']) ?? 0,
      isActive: SafeCasteUtil.safeCast<bool>(map['isActive']) ?? true,
    );
  }
}

/// Helper class for chained copyWith operations
class _AutoFromJsonTestCopyWith {
  final AutoFromJsonTest _instance;
  const _AutoFromJsonTestCopyWith._(this._instance);

  /// Update name field
  _AutoFromJsonTestCopyWith name(String value) {
    return _AutoFromJsonTestCopyWith._(AutoFromJsonTest(
      name: value,
      age: _instance.age,
      isActive: _instance.isActive,
    ));
  }

  /// Update age field
  _AutoFromJsonTestCopyWith age(int value) {
    return _AutoFromJsonTestCopyWith._(AutoFromJsonTest(
      name: _instance.name,
      age: value,
      isActive: _instance.isActive,
    ));
  }

  /// Update isActive field
  _AutoFromJsonTestCopyWith isActive(bool value) {
    return _AutoFromJsonTestCopyWith._(AutoFromJsonTest(
      name: _instance.name,
      age: _instance.age,
      isActive: value,
    ));
  }

  /// Build the final instance
  AutoFromJsonTest build() {
    return _instance;
  }

  /// Traditional copyWith method
  AutoFromJsonTest call({
    String? name,
    int? age,
    bool? isActive,
  }) {
    return AutoFromJsonTest(
      name: name ?? _instance.name,
      age: age ?? _instance.age,
      isActive: isActive ?? _instance.isActive,
    );
  }
}
