// Generated by data class generator
// DO NOT MODIFY BY HAND

part of 'cross_file_test.dart';

mixin _UserProfile {
  abstract final int id;
  abstract final String name;
  abstract final TokenBean token;

  _UserProfileCopyWith get copyWith =>
      _UserProfileCopyWith._(this as UserProfile);

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    if (other is! UserProfile) return false;

    if (id != other.id) {
      return false;
    }
    if (name != other.name) {
      return false;
    }
    if (token != other.token) {
      return false;
    }
    return true;
  }

  @override
  int get hashCode {
    return Object.hashAll([
      id,
      name,
      token,
    ]);
  }

  @override
  String toString() {
    return 'UserProfile(id: $id, name: $name, token: $token)';
  }

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    map['id'] = id;
    map['name'] = name;
    map['token'] = token;
    return map;
  }

  static UserProfile fromJson(Map<String, dynamic> map) {
    return UserProfile(
      id: SafeCasteUtil.safeCast<int>(map['id']) ?? 0,
      name: SafeCasteUtil.safeCast<String>(map['name']) ?? "",
      token: TokenBean.fromJson((map['token'] ?? {}) as Map<String, dynamic>),
    );
  }
}

mixin _SessionData {
  abstract final String sessionId;
  abstract final UserProfile user;

  _SessionDataCopyWith get copyWith =>
      _SessionDataCopyWith._(this as SessionData);

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    if (other is! SessionData) return false;

    if (sessionId != other.sessionId) {
      return false;
    }
    if (user != other.user) {
      return false;
    }
    return true;
  }

  @override
  int get hashCode {
    return Object.hashAll([
      sessionId,
      user,
    ]);
  }

  @override
  String toString() {
    return 'SessionData(sessionId: $sessionId, user: $user)';
  }

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    map['sessionId'] = sessionId;
    map['user'] = user;
    return map;
  }

  static SessionData fromJson(Map<String, dynamic> map) {
    return SessionData(
      sessionId: SafeCasteUtil.safeCast<String>(map['sessionId']) ?? "",
      user: UserProfile.fromJson((map['user'] ?? {}) as Map<String, dynamic>),
    );
  }
}

/// Helper class for chained copyWith operations
class _UserProfileCopyWith {
  final UserProfile _instance;
  const _UserProfileCopyWith._(this._instance);

  /// Update id field
  _UserProfileCopyWith id(int value) {
    return _UserProfileCopyWith._(UserProfile(
      id: value,
      name: _instance.name,
      token: _instance.token,
    ));
  }

  /// Update name field
  _UserProfileCopyWith name(String value) {
    return _UserProfileCopyWith._(UserProfile(
      id: _instance.id,
      name: value,
      token: _instance.token,
    ));
  }

  /// Update token field
  _UserProfileCopyWith token(TokenBean value) {
    return _UserProfileCopyWith._(UserProfile(
      id: _instance.id,
      name: _instance.name,
      token: value,
    ));
  }

  /// Build the final instance
  UserProfile build() {
    return _instance;
  }

  /// Nested copyWith for token field
  _UserProfileNestedCopyWithToken get tokenBuilder {
    return _UserProfileNestedCopyWithToken._(_instance);
  }

  /// Update token_accessToken field
  _UserProfileCopyWith $token_accessToken(String value) {
    return _UserProfileCopyWith._(UserProfile(
      id: _instance.id,
      name: _instance.name,
      token: _instance.token.copyWith.accessToken(value).build(),
    ));
  }

  /// Update token_refreshToken field
  _UserProfileCopyWith $token_refreshToken(String value) {
    return _UserProfileCopyWith._(UserProfile(
      id: _instance.id,
      name: _instance.name,
      token: _instance.token.copyWith.refreshToken(value).build(),
    ));
  }

  /// Update token_expiresAt field
  _UserProfileCopyWith $token_expiresAt(DateTime value) {
    return _UserProfileCopyWith._(UserProfile(
      id: _instance.id,
      name: _instance.name,
      token: _instance.token.copyWith.expiresAt(value).build(),
    ));
  }

  /// Update token_tokenType field
  _UserProfileCopyWith $token_tokenType(String value) {
    return _UserProfileCopyWith._(UserProfile(
      id: _instance.id,
      name: _instance.name,
      token: _instance.token.copyWith.tokenType(value).build(),
    ));
  }

  /// Traditional copyWith method
  UserProfile call({
    int? id,
    String? name,
    TokenBean? token,
  }) {
    return UserProfile(
      id: id ?? _instance.id,
      name: name ?? _instance.name,
      token: token ?? _instance.token,
    );
  }
}

/// Nested copyWith helper class for token field
class _UserProfileNestedCopyWithToken {
  final UserProfile _instance;
  const _UserProfileNestedCopyWithToken._(this._instance);

  /// Update token field using a copyWith function
  UserProfile call(TokenBean Function(TokenBean) updater) {
    final currentValue = _instance.token;
    final updatedValue = updater(currentValue);
    return UserProfile(
      id: _instance.id,
      name: _instance.name,
      token: updatedValue,
    );
  }
}

/// Helper class for chained copyWith operations
class _SessionDataCopyWith {
  final SessionData _instance;
  const _SessionDataCopyWith._(this._instance);

  /// Update sessionId field
  _SessionDataCopyWith sessionId(String value) {
    return _SessionDataCopyWith._(SessionData(
      sessionId: value,
      user: _instance.user,
    ));
  }

  /// Update user field
  _SessionDataCopyWith user(UserProfile value) {
    return _SessionDataCopyWith._(SessionData(
      sessionId: _instance.sessionId,
      user: value,
    ));
  }

  /// Build the final instance
  SessionData build() {
    return _instance;
  }

  /// Nested copyWith for user field
  _SessionDataNestedCopyWithUser get userBuilder {
    return _SessionDataNestedCopyWithUser._(_instance);
  }

  /// Update user_id field
  _SessionDataCopyWith $user_id(int value) {
    return _SessionDataCopyWith._(SessionData(
      sessionId: _instance.sessionId,
      user: _instance.user.copyWith.id(value).build(),
    ));
  }

  /// Update user_name field
  _SessionDataCopyWith $user_name(String value) {
    return _SessionDataCopyWith._(SessionData(
      sessionId: _instance.sessionId,
      user: _instance.user.copyWith.name(value).build(),
    ));
  }

  /// Update user_token_accessToken field
  _SessionDataCopyWith $user_token_accessToken(String value) {
    return _SessionDataCopyWith._(SessionData(
      sessionId: _instance.sessionId,
      user: _instance.user.copyWith
          .token(_instance.user.token.copyWith.accessToken(value).build())
          .build(),
    ));
  }

  /// Update user_token_refreshToken field
  _SessionDataCopyWith $user_token_refreshToken(String value) {
    return _SessionDataCopyWith._(SessionData(
      sessionId: _instance.sessionId,
      user: _instance.user.copyWith
          .token(_instance.user.token.copyWith.refreshToken(value).build())
          .build(),
    ));
  }

  /// Update user_token_expiresAt field
  _SessionDataCopyWith $user_token_expiresAt(DateTime value) {
    return _SessionDataCopyWith._(SessionData(
      sessionId: _instance.sessionId,
      user: _instance.user.copyWith
          .token(_instance.user.token.copyWith.expiresAt(value).build())
          .build(),
    ));
  }

  /// Update user_token_tokenType field
  _SessionDataCopyWith $user_token_tokenType(String value) {
    return _SessionDataCopyWith._(SessionData(
      sessionId: _instance.sessionId,
      user: _instance.user.copyWith
          .token(_instance.user.token.copyWith.tokenType(value).build())
          .build(),
    ));
  }

  /// Traditional copyWith method
  SessionData call({
    String? sessionId,
    UserProfile? user,
  }) {
    return SessionData(
      sessionId: sessionId ?? _instance.sessionId,
      user: user ?? _instance.user,
    );
  }
}

/// Nested copyWith helper class for user field
class _SessionDataNestedCopyWithUser {
  final SessionData _instance;
  const _SessionDataNestedCopyWithUser._(this._instance);

  /// Update user field using a copyWith function
  SessionData call(UserProfile Function(UserProfile) updater) {
    final currentValue = _instance.user;
    final updatedValue = updater(currentValue);
    return SessionData(
      sessionId: _instance.sessionId,
      user: updatedValue,
    );
  }
}
