// Generated by data class generator
// DO NOT MODIFY BY HAND

part of 'cross_enum_model.dart';

mixin _CrossEnumTest {
  abstract final LocalStatus status;
  abstract final LocalPriority priority;
  abstract final List<LocalStatus> statusList;
  abstract final Map<String, LocalPriority> priorityMap;

  _CrossEnumTestCopyWith get copyWith =>
      _CrossEnumTestCopyWith._(this as CrossEnumTest);

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    if (other is! CrossEnumTest) return false;

    if (status != other.status) {
      return false;
    }
    if (priority != other.priority) {
      return false;
    }
    if (!DeepCollectionEquality().equals(statusList, other.statusList)) {
      return false;
    }
    if (!DeepCollectionEquality().equals(priorityMap, other.priorityMap)) {
      return false;
    }
    return true;
  }

  @override
  int get hashCode {
    return Object.hashAll([
      status,
      priority,
      DeepCollectionEquality().hash(statusList),
      DeepCollectionEquality().hash(priorityMap),
    ]);
  }

  @override
  String toString() {
    return 'CrossEnumTest(status: $status, priority: $priority, statusList: $statusList, priorityMap: $priorityMap)';
  }

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    map['status'] = const DefaultEnumConverter<LocalStatus>(LocalStatus.values)
        .toJson(status);
    map['priority'] =
        const DefaultEnumConverter<LocalPriority>(LocalPriority.values)
            .toJson(priority);
    map['statusList'] = statusList
        .map((e) => const DefaultEnumConverter<LocalStatus>(LocalStatus.values)
            .toJson(e))
        .toList();
    map['priorityMap'] = priorityMap.map((key, value) => MapEntry(
        key,
        const DefaultEnumConverter<LocalPriority>(LocalPriority.values)
            .toJson(value)));
    return map;
  }

  static CrossEnumTest fromJson(Map<String, dynamic> map) {
    return CrossEnumTest(
      status: map['status'] != null
          ? const DefaultEnumConverter<LocalStatus>(LocalStatus.values)
              .fromJson(map['status']) as LocalStatus
          : throw ArgumentError('Required field status is missing'),
      priority: map['priority'] != null
          ? const DefaultEnumConverter<LocalPriority>(LocalPriority.values)
              .fromJson(map['priority']) as LocalPriority
          : throw ArgumentError('Required field priority is missing'),
      statusList: (map['statusList'] as List<dynamic>?)
              ?.map((e) =>
                  const DefaultEnumConverter<LocalStatus>(LocalStatus.values)
                      .fromJson(e))
              .toList()
              .cast<LocalStatus>() ??
          [],
      priorityMap: (map['priorityMap'] as Map<String, dynamic>?)?.map(
              (key, value) => MapEntry(
                  key,
                  const DefaultEnumConverter<LocalPriority>(
                          LocalPriority.values)
                      .fromJson(value)!)) ??
          {},
    );
  }
}

/// Helper class for chained copyWith operations
class _CrossEnumTestCopyWith {
  final CrossEnumTest _instance;
  const _CrossEnumTestCopyWith._(this._instance);

  /// Update status field
  _CrossEnumTestCopyWith status(LocalStatus value) {
    return _CrossEnumTestCopyWith._(CrossEnumTest(
      status: value,
      priority: _instance.priority,
      statusList: _instance.statusList,
      priorityMap: _instance.priorityMap,
    ));
  }

  /// Update priority field
  _CrossEnumTestCopyWith priority(LocalPriority value) {
    return _CrossEnumTestCopyWith._(CrossEnumTest(
      status: _instance.status,
      priority: value,
      statusList: _instance.statusList,
      priorityMap: _instance.priorityMap,
    ));
  }

  /// Update statusList field
  _CrossEnumTestCopyWith statusList(List<LocalStatus> value) {
    return _CrossEnumTestCopyWith._(CrossEnumTest(
      status: _instance.status,
      priority: _instance.priority,
      statusList: value,
      priorityMap: _instance.priorityMap,
    ));
  }

  /// Update priorityMap field
  _CrossEnumTestCopyWith priorityMap(Map<String, LocalPriority> value) {
    return _CrossEnumTestCopyWith._(CrossEnumTest(
      status: _instance.status,
      priority: _instance.priority,
      statusList: _instance.statusList,
      priorityMap: value,
    ));
  }

  /// Build the final instance
  CrossEnumTest build() {
    return _instance;
  }

  /// Traditional copyWith method
  CrossEnumTest call({
    LocalStatus? status,
    LocalPriority? priority,
    List<LocalStatus>? statusList,
    Map<String, LocalPriority>? priorityMap,
  }) {
    return CrossEnumTest(
      status: status ?? _instance.status,
      priority: priority ?? _instance.priority,
      statusList: statusList ?? _instance.statusList,
      priorityMap: priorityMap ?? _instance.priorityMap,
    );
  }
}
