// Generated by data class generator
// DO NOT MODIFY BY HAND

part of 'defalt_converter.dart';

mixin _Test {
  abstract final DateTime createdAt;
  abstract final DateTime? createdAtNull;

  _TestCopyWith get copyWith => _TestCopyWith._(this);

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    if (other is! Test) return false;

    if (createdAt != other.createdAt) {
      return false;
    }
    if (createdAtNull != other.createdAtNull) {
      return false;
    }
    return true;
  }

  @override
  int get hashCode {
    return Object.hashAll([
      createdAt,
      createdAtNull,
    ]);
  }

  @override
  String toString() {
    return 'Test(createdAt: $createdAt, createdAtNull: $createdAtNull)';
  }

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    map['createdAt'] = const DefaultDateTimeConverter().toJson(createdAt);
    if (createdAtNull != null) {
      map['createdAtNull'] = createdAtNull != null
          ? const DefaultDateTimeConverter().toJson(createdAtNull!)
          : null;
    }
    return map;
  }

  static Test fromJson(Map<String, dynamic> map) {
    return Test(
      createdAt: map['createdAt'] != null
          ? const DefaultDateTimeConverter().fromJson(map['createdAt'])
              as DateTime
          : throw ArgumentError('Required field createdAt is missing'),
      createdAtNull: map['createdAtNull'] != null
          ? const DefaultDateTimeConverter().fromJson(map['createdAtNull'])
          : null,
    );
  }
}

/// Helper class for chained copyWith operations
class _TestCopyWith {
  final _Test _instance;
  const _TestCopyWith._(this._instance);

  /// Update createdAt field
  Test createdAt(DateTime? value) {
    return Test(
      createdAt: value ?? _instance.createdAt,
      createdAtNull: _instance.createdAtNull,
    );
  }

  /// Update createdAtNull field
  Test createdAtNull(DateTime? value) {
    return Test(
      createdAt: _instance.createdAt,
      createdAtNull: value,
    );
  }

  /// Traditional copyWith method
  Test call({
    DateTime? createdAt,
    DateTime? createdAtNull,
  }) {
    return Test(
      createdAt: createdAt ?? _instance.createdAt,
      createdAtNull: createdAtNull ?? _instance.createdAtNull,
    );
  }
}
