// Generated by data class generator
// DO NOT MODIFY BY HAND

part of 'enum_import_model.dart';

mixin _EnumImportTest {
  abstract final LocalStatus status;
  abstract final LocalPriority priority;
  abstract final List<LocalStatus> statusList;
  abstract final Map<String, LocalPriority> priorityMap;

  _EnumImportTestCopyWith get copyWith =>
      _EnumImportTestCopyWith._(this as EnumImportTest);

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    if (other is! EnumImportTest) return false;

    if (status != other.status) {
      return false;
    }
    if (priority != other.priority) {
      return false;
    }
    if (!DeepCollectionEquality().equals(statusList, other.statusList)) {
      return false;
    }
    if (!DeepCollectionEquality().equals(priorityMap, other.priorityMap)) {
      return false;
    }
    return true;
  }

  @override
  int get hashCode {
    return Object.hashAll([
      status,
      priority,
      DeepCollectionEquality().hash(statusList),
      DeepCollectionEquality().hash(priorityMap),
    ]);
  }

  @override
  String toString() {
    return 'EnumImportTest(status: $status, priority: $priority, statusList: $statusList, priorityMap: $priorityMap)';
  }

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    map['status'] = const DefaultEnumConverter<LocalStatus>(LocalStatus.values)
        .toJson(status);
    map['priority'] =
        const DefaultEnumConverter<LocalPriority>(LocalPriority.values)
            .toJson(priority);
    map['statusList'] = statusList
        .map((e) => const DefaultEnumConverter<LocalStatus>(LocalStatus.values)
            .toJson(e))
        .toList();
    map['priorityMap'] = priorityMap.map((key, value) => MapEntry(
        key,
        const DefaultEnumConverter<LocalPriority>(LocalPriority.values)
            .toJson(value)));
    return map;
  }

  static EnumImportTest fromJson(Map<String, dynamic> map) {
    return EnumImportTest(
      status: map['status'] != null
          ? const DefaultEnumConverter<LocalStatus>(LocalStatus.values)
              .fromJson(map['status']) as LocalStatus
          : throw ArgumentError('Required field status is missing'),
      priority: map['priority'] != null
          ? const DefaultEnumConverter<LocalPriority>(LocalPriority.values)
              .fromJson(map['priority']) as LocalPriority
          : throw ArgumentError('Required field priority is missing'),
      statusList: (map['statusList'] as List<dynamic>?)
              ?.map((e) =>
                  const DefaultEnumConverter<LocalStatus>(LocalStatus.values)
                      .fromJson(e))
              .toList()
              .cast<LocalStatus>() ??
          [],
      priorityMap: (map['priorityMap'] as Map<String, dynamic>?)?.map(
              (key, value) => MapEntry(
                  key,
                  const DefaultEnumConverter<LocalPriority>(
                          LocalPriority.values)
                      .fromJson(value)!)) ??
          {},
    );
  }
}

/// Helper class for chained copyWith operations
class _EnumImportTestCopyWith {
  final EnumImportTest _instance;
  const _EnumImportTestCopyWith._(this._instance);

  /// Update status field
  _EnumImportTestCopyWith status(LocalStatus value) {
    return _EnumImportTestCopyWith._(EnumImportTest(
      status: value,
      priority: _instance.priority,
      statusList: _instance.statusList,
      priorityMap: _instance.priorityMap,
    ));
  }

  /// Update priority field
  _EnumImportTestCopyWith priority(LocalPriority value) {
    return _EnumImportTestCopyWith._(EnumImportTest(
      status: _instance.status,
      priority: value,
      statusList: _instance.statusList,
      priorityMap: _instance.priorityMap,
    ));
  }

  /// Update statusList field
  _EnumImportTestCopyWith statusList(List<LocalStatus> value) {
    return _EnumImportTestCopyWith._(EnumImportTest(
      status: _instance.status,
      priority: _instance.priority,
      statusList: value,
      priorityMap: _instance.priorityMap,
    ));
  }

  /// Update priorityMap field
  _EnumImportTestCopyWith priorityMap(Map<String, LocalPriority> value) {
    return _EnumImportTestCopyWith._(EnumImportTest(
      status: _instance.status,
      priority: _instance.priority,
      statusList: _instance.statusList,
      priorityMap: value,
    ));
  }

  /// Build the final instance
  EnumImportTest build() {
    return _instance;
  }

  /// Nested copyWith for status field
  _EnumImportTestNestedCopyWithStatus get statusBuilder {
    return _EnumImportTestNestedCopyWithStatus._(_instance);
  }

  /// Nested copyWith for priority field
  _EnumImportTestNestedCopyWithPriority get priorityBuilder {
    return _EnumImportTestNestedCopyWithPriority._(_instance);
  }

  /// Traditional copyWith method
  EnumImportTest call({
    LocalStatus? status,
    LocalPriority? priority,
    List<LocalStatus>? statusList,
    Map<String, LocalPriority>? priorityMap,
  }) {
    return EnumImportTest(
      status: status ?? _instance.status,
      priority: priority ?? _instance.priority,
      statusList: statusList ?? _instance.statusList,
      priorityMap: priorityMap ?? _instance.priorityMap,
    );
  }
}

/// Nested copyWith helper class for status field
class _EnumImportTestNestedCopyWithStatus {
  final EnumImportTest _instance;
  const _EnumImportTestNestedCopyWithStatus._(this._instance);

  /// Update status field using a copyWith function
  EnumImportTest call(LocalStatus Function(LocalStatus) updater) {
    final currentValue = _instance.status;
    final updatedValue = updater(currentValue);
    return EnumImportTest(
      status: updatedValue,
      priority: _instance.priority,
      statusList: _instance.statusList,
      priorityMap: _instance.priorityMap,
    );
  }
}

/// Nested copyWith helper class for priority field
class _EnumImportTestNestedCopyWithPriority {
  final EnumImportTest _instance;
  const _EnumImportTestNestedCopyWithPriority._(this._instance);

  /// Update priority field using a copyWith function
  EnumImportTest call(LocalPriority Function(LocalPriority) updater) {
    final currentValue = _instance.priority;
    final updatedValue = updater(currentValue);
    return EnumImportTest(
      status: _instance.status,
      priority: updatedValue,
      statusList: _instance.statusList,
      priorityMap: _instance.priorityMap,
    );
  }
}
