// Generated by data class generator
// DO NOT MODIFY BY HAND

part of 'enum_types.model.dart';

mixin _EnumTypes {
  abstract final Status status;
  abstract final UserRole? optionalRole;
  abstract final UserRole userType;
  abstract final Priority priority;
  abstract final Status parsedStatus;
  abstract final UserRole? roleFromInt;
  abstract final List<Status>? statusList;
  abstract final Map<String, UserRole>? roleMap;

  EnumTypes copyWith({
    Status? status,
    UserRole? optionalRole,
    UserRole? userType,
    Priority? priority,
    Status? parsedStatus,
    UserRole? roleFromInt,
    List<Status>? statusList,
    Map<String, UserRole>? roleMap,
  }) {
    return EnumTypes(
      status: status ?? this.status,
      optionalRole: optionalRole ?? this.optionalRole,
      userType: userType ?? this.userType,
      priority: priority ?? this.priority,
      parsedStatus: parsedStatus ?? this.parsedStatus,
      roleFromInt: roleFromInt ?? this.roleFromInt,
      statusList: statusList ?? this.statusList,
      roleMap: roleMap ?? this.roleMap,
    );
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    if (other is! EnumTypes) return false;

    if (status != other.status) {
      return false;
    }
    if (optionalRole != other.optionalRole) {
      return false;
    }
    if (userType != other.userType) {
      return false;
    }
    if (priority != other.priority) {
      return false;
    }
    if (parsedStatus != other.parsedStatus) {
      return false;
    }
    if (roleFromInt != other.roleFromInt) {
      return false;
    }
    if (!DeepCollectionEquality().equals(statusList, other.statusList)) {
      return false;
    }
    if (!DeepCollectionEquality().equals(roleMap, other.roleMap)) {
      return false;
    }
    return true;
  }

  @override
  int get hashCode {
    return Object.hashAll([
      status,
      optionalRole,
      userType,
      priority,
      parsedStatus,
      roleFromInt,
      DeepCollectionEquality().hash(statusList),
      DeepCollectionEquality().hash(roleMap),
    ]);
  }

  @override
  String toString() {
    return 'EnumTypes(status: $status, optionalRole: $optionalRole, userType: $userType, priority: $priority, parsedStatus: $parsedStatus, roleFromInt: $roleFromInt, statusList: $statusList, roleMap: $roleMap)';
  }

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    map['status'] = const EnumConverter(Status.values).toJson(status);
    if (optionalRole != null) {
      map['optionalRole'] = optionalRole != null
          ? const EnumConverter(UserRole.values).toJson(optionalRole!)
          : null;
    }
    map['user_type'] = const EnumConverter(UserRole.values).toJson(userType);
    map['priority'] = const EnumConverter(Priority.values).toJson(priority);
    map['parsedStatus'] =
        const EnumConverter(Status.values).toJson(parsedStatus);
    if (roleFromInt != null) {
      map['roleFromInt'] = roleFromInt != null
          ? const EnumConverter(UserRole.values).toJson(roleFromInt!)
          : null;
    }
    if (statusList != null) {
      map['statusList'] = statusList;
    }
    if (roleMap != null) {
      map['roleMap'] = roleMap;
    }
    return map;
  }

  static EnumTypes fromJson(Map<String, dynamic> map) {
    return EnumTypes(
      status: map['status'] != null
          ? const EnumConverter(Status.values).fromJson(map['status'])
          : throw ArgumentError('Required field status is missing'),
      optionalRole: map['optionalRole'] != null
          ? const EnumConverter(UserRole.values).fromJson(map['optionalRole'])
          : null,
      userType: map['user_type'] != null
          ? const EnumConverter(UserRole.values).fromJson(map['user_type'])
          : throw ArgumentError('Required field userType is missing'),
      priority: map['priority'] != null
          ? const EnumConverter(Priority.values).fromJson(map['priority'])
          : throw ArgumentError('Required field priority is missing'),
      parsedStatus: map['parsedStatus'] != null
          ? const EnumConverter(Status.values).fromJson(map['parsedStatus'])
          : throw ArgumentError('Required field parsedStatus is missing'),
      roleFromInt: EnumTypes._readValue(map, 'roleFromInt') as UserRole?,
      statusList: (map['statusList'] as List<dynamic>?)
          ?.map((e) => const EnumConverter(Status.values).fromJson(e))
          .toList()
          .cast<Status>(),
      roleMap: (map['roleMap'] as Map<String, dynamic>?)?.map((key, value) =>
          MapEntry(key, const EnumConverter(UserRole.values).fromJson(value))),
    );
  }
}
