// Generated by data class generator
// DO NOT MODIFY BY HAND

part of 'enum_types.model.dart';

mixin _EnumTypes {
  abstract final Status status;
  abstract final UserRole? optionalRole;
  abstract final UserRole userType;
  abstract final Priority priority;
  abstract final Status parsedStatus;
  abstract final UserRole? roleFromInt;
  abstract final List<Status>? statusList;
  abstract final Map<String, UserRole>? roleMap;

  EnumTypes copyWith({
    Status? status,
    UserRole? optionalRole,
    UserRole? userType,
    Priority? priority,
    Status? parsedStatus,
    UserRole? roleFromInt,
    List<Status>? statusList,
    Map<String, UserRole>? roleMap,
  }) {
    return EnumTypes(
      status: status ?? this.status,
      optionalRole: optionalRole ?? this.optionalRole,
      userType: userType ?? this.userType,
      priority: priority ?? this.priority,
      parsedStatus: parsedStatus ?? this.parsedStatus,
      roleFromInt: roleFromInt ?? this.roleFromInt,
      statusList: statusList ?? this.statusList,
      roleMap: roleMap ?? this.roleMap,
    );
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    if (other is! EnumTypes) return false;

    if (status != other.status) {
      return false;
    }
    if (optionalRole != other.optionalRole) {
      return false;
    }
    if (userType != other.userType) {
      return false;
    }
    if (priority != other.priority) {
      return false;
    }
    if (parsedStatus != other.parsedStatus) {
      return false;
    }
    if (roleFromInt != other.roleFromInt) {
      return false;
    }
    if (!const DeepCollectionEquality().equals(statusList, other.statusList)) {
      return false;
    }
    if (!const DeepCollectionEquality().equals(roleMap, other.roleMap)) {
      return false;
    }
    return true;
  }

  @override
  int get hashCode {
    return Object.hashAll([
      status,
      optionalRole,
      userType,
      priority,
      parsedStatus,
      roleFromInt,
      const DeepCollectionEquality().hash(statusList),
      const DeepCollectionEquality().hash(roleMap),
    ]);
  }

  @override
  String toString() {
    return 'EnumTypes(status: $status, optionalRole: $optionalRole, userType: $userType, priority: $priority, parsedStatus: $parsedStatus, roleFromInt: $roleFromInt, statusList: $statusList, roleMap: $roleMap)';
  }

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    map['status'] = status;
    map['optionalRole'] = optionalRole;
    map['user_type'] = userType;
    map['priority'] = priority;
    map['parsedStatus'] = parsedStatus;
    map['roleFromInt'] = roleFromInt;
    map['statusList'] = statusList;
    map['roleMap'] = roleMap;
    return map;
  }

  static EnumTypes fromJson(Map<String, dynamic> map) {
    return EnumTypes(
      status: (map['status'] as Status),
      optionalRole: (map['optionalRole'] as UserRole?),
      userType: (map['user_type'] as UserRole),
      priority: (map['priority'] as Priority),
      parsedStatus: (EnumTypes._readValue(map, 'parsedStatus')) as Status,
      roleFromInt: EnumTypes._readValue(map, 'roleFromInt') as UserRole?,
      statusList: (map['statusList'] as List<dynamic>?)?.cast<Status>(),
      roleMap: (map['roleMap'] as Map<String, UserRole>?),
    );
  }
}
