// Generated by data class generator
// DO NOT MODIFY BY HAND

part of 'example_ignore_validation.example.dart';

mixin _ValidExample1 {
  abstract final String name;
  abstract final String? password;

  ValidExample1 copyWith({
    String? name,
    String? password,
  }) {
    return ValidExample1(
      name: name ?? this.name,
      password: password ?? this.password,
    );
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    if (other is! ValidExample1) return false;

    if (name != other.name) {
      return false;
    }
    if (password != other.password) {
      return false;
    }
    return true;
  }

  @override
  int get hashCode {
    return Object.hashAll([
      name,
      password,
    ]);
  }
  @override
  String toString() {
    return 'ValidExample1(name: $name, password: $password)';
  }


  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    map['name'] = name;
    return map;
  }

  static ValidExample1 fromJson(Map<String, dynamic> map) {
    return ValidExample1(
      name: (map['name'])?.toString() ?? "",
    );
  }
}

mixin _ValidExample2 {
  abstract final String name;
  abstract final String secret;

  ValidExample2 copyWith({
    String? name,
    String? secret,
  }) {
    return ValidExample2(
      name: name ?? this.name,
      secret: secret ?? this.secret,
    );
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    if (other is! ValidExample2) return false;

    if (name != other.name) {
      return false;
    }
    if (secret != other.secret) {
      return false;
    }
    return true;
  }

  @override
  int get hashCode {
    return Object.hashAll([
      name,
      secret,
    ]);
  }
  @override
  String toString() {
    return 'ValidExample2(name: $name, secret: $secret)';
  }


  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    map['name'] = name;
    return map;
  }

  static ValidExample2 fromJson(Map<String, dynamic> map) {
    return ValidExample2(
      name: (map['name'])?.toString() ?? "",
    );
  }
}

