// Generated by data class generator
// DO NOT MODIFY BY HAND

part of 'generic_support_test.model.dart';

mixin _GenericContainer<T> {
  abstract final T data;
  abstract final String name;
  abstract final int? count;

  GenericContainer<T> copyWith({
    T? data,
    String? name,
    int? count,
  }) {
    return GenericContainer<T>(
      data: data ?? this.data,
      name: name ?? this.name,
      count: count ?? this.count,
    );
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    if (other is! GenericContainer) return false;

    if (data != other.data) {
      return false;
    }
    if (name != other.name) {
      return false;
    }
    if (count != other.count) {
      return false;
    }
    return true;
  }

  @override
  int get hashCode {
    return Object.hashAll([
      data,
      name,
      count,
    ]);
  }

  @override
  String toString() {
    return 'GenericContainer(data: $data, name: $name, count: $count)';
  }

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    map['data'] = data;
    map['name'] = name;
    if (count != null) {
      map['count'] = count;
    }
    return map;
  }

  static GenericContainer<T> fromJson<T>(Map<String, dynamic> map) {
    return GenericContainer<T>(
      data: map['data'] as T,
      name: SafeCasteUtil.safeCast<String>(map['name']) ?? "",
      count: SafeCasteUtil.safeCast<int>(map['count']),
    );
  }
}

mixin _GenericPair<T, U> {
  abstract final T first;
  abstract final U second;
  abstract final String label;

  GenericPair<T, U> copyWith({
    T? first,
    U? second,
    String? label,
  }) {
    return GenericPair<T, U>(
      first: first ?? this.first,
      second: second ?? this.second,
      label: label ?? this.label,
    );
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    if (other is! GenericPair) return false;

    if (first != other.first) {
      return false;
    }
    if (second != other.second) {
      return false;
    }
    if (label != other.label) {
      return false;
    }
    return true;
  }

  @override
  int get hashCode {
    return Object.hashAll([
      first,
      second,
      label,
    ]);
  }

  @override
  String toString() {
    return 'GenericPair(first: $first, second: $second, label: $label)';
  }

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    map['first'] = first;
    map['second'] = second;
    map['label'] = label;
    return map;
  }

  static GenericPair<T, U> fromJson<T, U>(Map<String, dynamic> map) {
    return GenericPair<T, U>(
      first: map['first'] as T,
      second: map['second'] as U,
      label: SafeCasteUtil.safeCast<String>(map['label']) ?? "",
    );
  }
}

mixin _GenericWrapper<T> {
  abstract final List<T> items;
  abstract final Map<String, T> namedItems;
  abstract final T? optionalItem;

  GenericWrapper<T> copyWith({
    List<T>? items,
    Map<String, T>? namedItems,
    T? optionalItem,
  }) {
    return GenericWrapper<T>(
      items: items ?? this.items,
      namedItems: namedItems ?? this.namedItems,
      optionalItem: optionalItem ?? this.optionalItem,
    );
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    if (other is! GenericWrapper) return false;

    if (!DeepCollectionEquality().equals(items, other.items)) {
      return false;
    }
    if (!DeepCollectionEquality().equals(namedItems, other.namedItems)) {
      return false;
    }
    if (optionalItem != other.optionalItem) {
      return false;
    }
    return true;
  }

  @override
  int get hashCode {
    return Object.hashAll([
      DeepCollectionEquality().hash(items),
      DeepCollectionEquality().hash(namedItems),
      optionalItem,
    ]);
  }

  @override
  String toString() {
    return 'GenericWrapper(items: $items, namedItems: $namedItems, optionalItem: $optionalItem)';
  }

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    map['items'] = items;
    map['namedItems'] = namedItems;
    if (optionalItem != null) {
      map['optionalItem'] = optionalItem;
    }
    return map;
  }

  static GenericWrapper<T> fromJson<T>(Map<String, dynamic> map) {
    return GenericWrapper<T>(
      items: (map['items'] as List<dynamic>?)?.cast<T>() ?? [],
      namedItems: ((map['namedItems'] as Map<dynamic, dynamic>?) ?? {})
          .map((key, value) => MapEntry(key as String, value as T)),
      optionalItem: map['optionalItem'] as T?,
    );
  }
}

mixin _GenericBounded<T> {
  abstract final T value;
  abstract final List<T> values;

  GenericBounded<T> copyWith({
    T? value,
    List<T>? values,
  }) {
    return GenericBounded<T>(
      value: value ?? this.value,
      values: values ?? this.values,
    );
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    if (other is! GenericBounded) return false;

    if (value != other.value) {
      return false;
    }
    if (!DeepCollectionEquality().equals(values, other.values)) {
      return false;
    }
    return true;
  }

  @override
  int get hashCode {
    return Object.hashAll([
      value,
      DeepCollectionEquality().hash(values),
    ]);
  }

  @override
  String toString() {
    return 'GenericBounded(value: $value, values: $values)';
  }

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    map['value'] = value;
    map['values'] = values;
    return map;
  }

  static GenericBounded<T> fromJson<T>(Map<String, dynamic> map) {
    return GenericBounded<T>(
      value: map['value'] as T,
      values: (map['values'] as List<dynamic>?)?.cast<T>() ?? [],
    );
  }
}

mixin _GenericWithFeatures<T> {
  abstract final T data;
  abstract final String customField;
  abstract final String ignoredField;
  abstract final TestStatus status;
  abstract final DateTime createdAt;

  GenericWithFeatures<T> copyWith({
    T? data,
    String? customField,
    String? ignoredField,
    TestStatus? status,
    DateTime? createdAt,
  }) {
    return GenericWithFeatures<T>(
      data: data ?? this.data,
      customField: customField ?? this.customField,
      ignoredField: ignoredField ?? this.ignoredField,
      status: status ?? this.status,
      createdAt: createdAt ?? this.createdAt,
    );
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    if (other is! GenericWithFeatures) return false;

    if (data != other.data) {
      return false;
    }
    if (customField != other.customField) {
      return false;
    }
    if (ignoredField != other.ignoredField) {
      return false;
    }
    if (status != other.status) {
      return false;
    }
    if (createdAt != other.createdAt) {
      return false;
    }
    return true;
  }

  @override
  int get hashCode {
    return Object.hashAll([
      data,
      customField,
      ignoredField,
      status,
      createdAt,
    ]);
  }

  @override
  String toString() {
    return 'GenericWithFeatures(data: $data, customField: $customField, ignoredField: $ignoredField, status: $status, createdAt: $createdAt)';
  }

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    map['data'] = data;
    map['custom_name'] = customField;
    map['status'] = const EnumConverter(TestStatus.values).toJson(status);
    map['createdAt'] = const DateTimeConverter().toJson(createdAt);
    return map;
  }

  static GenericWithFeatures<T> fromJson<T>(Map<String, dynamic> map) {
    return GenericWithFeatures<T>(
      data: map['data'] as T,
      customField: SafeCasteUtil.safeCast<String>(map['custom_name']) ?? "",
      status: map['status'] != null
          ? const EnumConverter(TestStatus.values).fromJson(map['status'])
          : throw ArgumentError('Required field status is missing'),
      createdAt: map['createdAt'] != null
          ? const DateTimeConverter().fromJson(map['createdAt'])
          : throw ArgumentError('Required field createdAt is missing'),
    );
  }
}
