// Generated by data class generator
// DO NOT MODIFY BY HAND

part of 'ignore_test.model.dart';

mixin _IgnoreTest {
  abstract final String name;
  abstract final String? password;
  abstract final int age;
  abstract final String? secretToken;
  abstract final bool isActive;

  _IgnoreTestCopyWith get copyWith => _IgnoreTestCopyWith._(this);

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    if (other is! IgnoreTest) return false;

    if (name != other.name) {
      return false;
    }
    if (password != other.password) {
      return false;
    }
    if (age != other.age) {
      return false;
    }
    if (secretToken != other.secretToken) {
      return false;
    }
    if (isActive != other.isActive) {
      return false;
    }
    return true;
  }

  @override
  int get hashCode {
    return Object.hashAll([
      name,
      password,
      age,
      secretToken,
      isActive,
    ]);
  }

  @override
  String toString() {
    return 'IgnoreTest(name: $name, password: $password, age: $age, secretToken: $secretToken, isActive: $isActive)';
  }

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    map['name'] = name;
    map['age'] = age;
    map['isActive'] = isActive;
    return map;
  }

  static IgnoreTest fromJson(Map<String, dynamic> map) {
    return IgnoreTest(
      name: SafeCasteUtil.safeCast<String>(map['name']) ?? "",
      age: SafeCasteUtil.safeCast<int>(map['age']) ?? 0,
      isActive: SafeCasteUtil.safeCast<bool>(map['isActive']) ?? false,
    );
  }
}

/// Helper class for chained copyWith operations
class _IgnoreTestCopyWith {
  final _IgnoreTest _instance;
  const _IgnoreTestCopyWith._(this._instance);

  /// Update name field
  IgnoreTest name(String? value) {
    return IgnoreTest(
      name: value ?? _instance.name,
      password: _instance.password,
      age: _instance.age,
      secretToken: _instance.secretToken,
      isActive: _instance.isActive,
    );
  }

  /// Update password field
  IgnoreTest password(String? value) {
    return IgnoreTest(
      name: _instance.name,
      password: value,
      age: _instance.age,
      secretToken: _instance.secretToken,
      isActive: _instance.isActive,
    );
  }

  /// Update age field
  IgnoreTest age(int? value) {
    return IgnoreTest(
      name: _instance.name,
      password: _instance.password,
      age: value ?? _instance.age,
      secretToken: _instance.secretToken,
      isActive: _instance.isActive,
    );
  }

  /// Update secretToken field
  IgnoreTest secretToken(String? value) {
    return IgnoreTest(
      name: _instance.name,
      password: _instance.password,
      age: _instance.age,
      secretToken: value,
      isActive: _instance.isActive,
    );
  }

  /// Update isActive field
  IgnoreTest isActive(bool? value) {
    return IgnoreTest(
      name: _instance.name,
      password: _instance.password,
      age: _instance.age,
      secretToken: _instance.secretToken,
      isActive: value ?? _instance.isActive,
    );
  }

  /// Traditional copyWith method
  IgnoreTest call({
    String? name,
    String? password,
    int? age,
    String? secretToken,
    bool? isActive,
  }) {
    return IgnoreTest(
      name: name ?? _instance.name,
      password: password ?? _instance.password,
      age: age ?? _instance.age,
      secretToken: secretToken ?? _instance.secretToken,
      isActive: isActive ?? _instance.isActive,
    );
  }
}
