// Generated by data class generator
// DO NOT MODIFY BY HAND

part of 'ignore_test.dart';

mixin _IgnoreTest {
  abstract final String name;
  abstract final String? password;
  abstract final int age;
  abstract final String? secretToken;
  abstract final bool isActive;

  IgnoreTest copyWith({
    String? name,
    String? password,
    int? age,
    String? secretToken,
    bool? isActive,
  }) {
    return IgnoreTest(
      name: name ?? this.name,
      password: password ?? this.password,
      age: age ?? this.age,
      secretToken: secretToken ?? this.secretToken,
      isActive: isActive ?? this.isActive,
    );
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    if (other is! IgnoreTest) return false;

    if (name != other.name) {
      return false;
    }
    if (password != other.password) {
      return false;
    }
    if (age != other.age) {
      return false;
    }
    if (secretToken != other.secretToken) {
      return false;
    }
    if (isActive != other.isActive) {
      return false;
    }
    return true;
  }

  @override
  int get hashCode {
    return Object.hashAll([
      name,
      password,
      age,
      secretToken,
      isActive,
    ]);
  }
  @override
  String toString() {
    return 'IgnoreTest(name: $name, password: $password, age: $age, secretToken: $secretToken, isActive: $isActive)';
  }


  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    map['name'] = name;
    map['age'] = age;
    map['isActive'] = isActive;
    return map;
  }

  static IgnoreTest fromJson(Map<String, dynamic> map) {
    return IgnoreTest(
      name: (map['name'])?.toString() ?? "",
      age: int.tryParse((map['age'] ?? '').toString()) ?? 0,
      isActive: (map['isActive'] as bool?) ?? false,
    );
  }
}

