// Generated by data class generator
// DO NOT MODIFY BY HAND

part of 'no_fromjson_test.model.dart';

mixin _NoFromJsonTest {
  abstract final String name;
  abstract final int age;

  _NoFromJsonTestCopyWith get copyWith => _NoFromJsonTestCopyWith._(this);

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    if (other is! NoFromJsonTest) return false;

    if (name != other.name) {
      return false;
    }
    if (age != other.age) {
      return false;
    }
    return true;
  }

  @override
  int get hashCode {
    return Object.hashAll([
      name,
      age,
    ]);
  }

  @override
  String toString() {
    return 'NoFromJsonTest(name: $name, age: $age)';
  }

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    map['name'] = name;
    map['age'] = age;
    return map;
  }
}

/// Helper class for chained copyWith operations
class _NoFromJsonTestCopyWith {
  final _NoFromJsonTest _instance;
  const _NoFromJsonTestCopyWith._(this._instance);

  /// Update name field
  NoFromJsonTest name(String? value) {
    return NoFromJsonTest(
      name: value ?? _instance.name,
      age: _instance.age,
    );
  }

  /// Update age field
  NoFromJsonTest age(int? value) {
    return NoFromJsonTest(
      name: _instance.name,
      age: value ?? _instance.age,
    );
  }

  /// Traditional copyWith method
  NoFromJsonTest call({
    String? name,
    int? age,
  }) {
    return NoFromJsonTest(
      name: name ?? _instance.name,
      age: age ?? _instance.age,
    );
  }
}
