// Generated by data class generator
// DO NOT MODIFY BY HAND

part of 'override_test.model.dart';

mixin _OverrideTest {
  abstract final String id;
  abstract final String name;
  abstract final String email;
  abstract final int? age;
  abstract final bool isActive;

  OverrideTest copyWith({
    String? id,
    String? name,
    String? email,
    int? age,
    bool? isActive,
  }) {
    return OverrideTest(
      id: id ?? this.id,
      name: name ?? this.name,
      email: email ?? this.email,
      age: age ?? this.age,
      isActive: isActive ?? this.isActive,
    );
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    if (other is! OverrideTest) return false;

    if (id != other.id) {
      return false;
    }
    if (name != other.name) {
      return false;
    }
    if (email != other.email) {
      return false;
    }
    if (age != other.age) {
      return false;
    }
    if (isActive != other.isActive) {
      return false;
    }
    return true;
  }

  @override
  int get hashCode {
    return Object.hashAll([
      id,
      name,
      email,
      age,
      isActive,
    ]);
  }

  @override
  String toString() {
    return 'OverrideTest(id: $id, name: $name, email: $email, age: $age, isActive: $isActive)';
  }

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    map['id'] = id;
    map['name'] = name;
    map['email'] = email;
    map['age'] = age;
    map['isActive'] = isActive;
    return map;
  }

  static OverrideTest fromJson(Map<String, dynamic> map) {
    return OverrideTest(
      id: (map['id'])?.toString() ?? "",
      name: (map['name'])?.toString() ?? "",
      email: (map['email'])?.toString() ?? "",
      age: map['age'] != null ? int.tryParse(map['age'].toString()) : null,
      isActive: (map['isActive'] as bool?) ?? true,
    );
  }
}
