// Generated by data class generator
// DO NOT MODIFY BY HAND

part of 'prefix_validation_test.model.dart';

mixin _PrefixValidationTest {
  abstract final String name;
  abstract final int age;
  abstract final bool isActive;
  abstract final double score;
  abstract final String? description;
  abstract final String customField;
  abstract final String ignoredField;

  _PrefixValidationTestCopyWith get copyWith =>
      _PrefixValidationTestCopyWith._(this as PrefixValidationTest);

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    if (other is! PrefixValidationTest) return false;

    if (name != other.name) {
      return false;
    }
    if (age != other.age) {
      return false;
    }
    if (isActive != other.isActive) {
      return false;
    }
    if (score != other.score) {
      return false;
    }
    if (description != other.description) {
      return false;
    }
    if (customField != other.customField) {
      return false;
    }
    if (ignoredField != other.ignoredField) {
      return false;
    }
    return true;
  }

  @override
  int get hashCode {
    return Object.hashAll([
      name,
      age,
      isActive,
      score,
      description,
      customField,
      ignoredField,
    ]);
  }

  @override
  String toString() {
    return 'PrefixValidationTest(name: $name, age: $age, isActive: $isActive, score: $score, description: $description, customField: $customField, ignoredField: $ignoredField)';
  }

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    map['name'] = name;
    map['age'] = age;
    map['isActive'] = isActive;
    map['score'] = score;
    if (description != null) {
      map['description'] = description;
    }
    map['custom_field'] = customField;
    return map;
  }

  static PrefixValidationTest fromJson(Map<String, dynamic> map) {
    return PrefixValidationTest(
      name: dataforge_annotation.SafeCasteUtil.safeCast<String>(map['name']) ??
          "",
      age: dataforge_annotation.SafeCasteUtil.safeCast<int>(map['age']) ?? 0,
      isActive:
          dataforge_annotation.SafeCasteUtil.safeCast<bool>(map['isActive']) ??
              false,
      score:
          dataforge_annotation.SafeCasteUtil.safeCast<double>(map['score']) ??
              0.0,
      description: dataforge_annotation.SafeCasteUtil.safeCast<String>(
          map['description']),
      customField: dataforge_annotation.SafeCasteUtil.safeCast<String>(
              map['custom_field']) ??
          "",
    );
  }
}

/// Helper class for chained copyWith operations
class _PrefixValidationTestCopyWith {
  final PrefixValidationTest _instance;
  const _PrefixValidationTestCopyWith._(this._instance);

  /// Update name field
  _PrefixValidationTestCopyWith name(String value) {
    return _PrefixValidationTestCopyWith._(PrefixValidationTest(
      name: value,
      age: _instance.age,
      isActive: _instance.isActive,
      score: _instance.score,
      description: _instance.description,
      customField: _instance.customField,
      ignoredField: _instance.ignoredField,
    ));
  }

  /// Update age field
  _PrefixValidationTestCopyWith age(int value) {
    return _PrefixValidationTestCopyWith._(PrefixValidationTest(
      name: _instance.name,
      age: value,
      isActive: _instance.isActive,
      score: _instance.score,
      description: _instance.description,
      customField: _instance.customField,
      ignoredField: _instance.ignoredField,
    ));
  }

  /// Update isActive field
  _PrefixValidationTestCopyWith isActive(bool value) {
    return _PrefixValidationTestCopyWith._(PrefixValidationTest(
      name: _instance.name,
      age: _instance.age,
      isActive: value,
      score: _instance.score,
      description: _instance.description,
      customField: _instance.customField,
      ignoredField: _instance.ignoredField,
    ));
  }

  /// Update score field
  _PrefixValidationTestCopyWith score(double value) {
    return _PrefixValidationTestCopyWith._(PrefixValidationTest(
      name: _instance.name,
      age: _instance.age,
      isActive: _instance.isActive,
      score: value,
      description: _instance.description,
      customField: _instance.customField,
      ignoredField: _instance.ignoredField,
    ));
  }

  /// Update description field
  _PrefixValidationTestCopyWith description(String? value) {
    return _PrefixValidationTestCopyWith._(PrefixValidationTest(
      name: _instance.name,
      age: _instance.age,
      isActive: _instance.isActive,
      score: _instance.score,
      description: value,
      customField: _instance.customField,
      ignoredField: _instance.ignoredField,
    ));
  }

  /// Update customField field
  _PrefixValidationTestCopyWith customField(String value) {
    return _PrefixValidationTestCopyWith._(PrefixValidationTest(
      name: _instance.name,
      age: _instance.age,
      isActive: _instance.isActive,
      score: _instance.score,
      description: _instance.description,
      customField: value,
      ignoredField: _instance.ignoredField,
    ));
  }

  /// Update ignoredField field
  _PrefixValidationTestCopyWith ignoredField(String value) {
    return _PrefixValidationTestCopyWith._(PrefixValidationTest(
      name: _instance.name,
      age: _instance.age,
      isActive: _instance.isActive,
      score: _instance.score,
      description: _instance.description,
      customField: _instance.customField,
      ignoredField: value,
    ));
  }

  /// Build the final instance
  PrefixValidationTest build() {
    return _instance;
  }

  /// Traditional copyWith method
  PrefixValidationTest call({
    String? name,
    int? age,
    bool? isActive,
    double? score,
    String? description,
    String? customField,
    String? ignoredField,
  }) {
    return PrefixValidationTest(
      name: name ?? _instance.name,
      age: age ?? _instance.age,
      isActive: isActive ?? _instance.isActive,
      score: score ?? _instance.score,
      description: description ?? _instance.description,
      customField: customField ?? _instance.customField,
      ignoredField: ignoredField ?? _instance.ignoredField,
    );
  }
}
