// Generated by data class generator
// DO NOT MODIFY BY HAND

part of 'test_model.model.dart';

mixin _TestModel {
  abstract final String name;
  abstract final Params? param;

  TestModel copyWith({
    String? name,
    Params? param,
  }) {
    return TestModel(
      name: name ?? this.name,
      param: param ?? this.param,
    );
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    if (other is! TestModel) return false;

    if (name != other.name) {
      return false;
    }
    if (param != other.param) {
      return false;
    }
    return true;
  }

  @override
  int get hashCode {
    return Object.hashAll([
      name,
      param,
    ]);
  }

  @override
  String toString() {
    return 'TestModel(name: $name, param: $param)';
  }

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    map['name'] = name;
    if (param != null) {
      map['param'] = param;
    }
    return map;
  }

  static TestModel fromJson(Map<String, dynamic> map) {
    return TestModel(
      name: SafeCasteUtil.safeCast<String>(map['name']) ?? "",
      param: map['param'] != null
          ? Params.fromJson(map['param'] as Map<String, dynamic>)
          : null,
    );
  }
}

mixin _Params {
  abstract final String value;

  Params copyWith({
    String? value,
  }) {
    return Params(
      value: value ?? this.value,
    );
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    if (other is! Params) return false;

    if (value != other.value) {
      return false;
    }
    return true;
  }

  @override
  int get hashCode {
    return Object.hashAll([
      value,
    ]);
  }

  @override
  String toString() {
    return 'Params(value: $value)';
  }

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    map['value'] = value;
    return map;
  }

  static Params fromJson(Map<String, dynamic> map) {
    return Params(
      value: SafeCasteUtil.safeCast<String>(map['value']) ?? "",
    );
  }
}
