// Generated by data class generator
// DO NOT MODIFY BY HAND

part of 'valid_ignore_test.model.dart';

mixin _ValidIgnoreTest {
  abstract final String name;
  abstract final String? nullablePassword;
  abstract final String passwordWithDefault;
  abstract final int age;

  _ValidIgnoreTestCopyWith get copyWith =>
      _ValidIgnoreTestCopyWith._(this as ValidIgnoreTest);

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    if (other is! ValidIgnoreTest) return false;

    if (name != other.name) {
      return false;
    }
    if (nullablePassword != other.nullablePassword) {
      return false;
    }
    if (passwordWithDefault != other.passwordWithDefault) {
      return false;
    }
    if (age != other.age) {
      return false;
    }
    return true;
  }

  @override
  int get hashCode {
    return Object.hashAll([
      name,
      nullablePassword,
      passwordWithDefault,
      age,
    ]);
  }

  @override
  String toString() {
    return 'ValidIgnoreTest(name: $name, nullablePassword: $nullablePassword, passwordWithDefault: $passwordWithDefault, age: $age)';
  }

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    map['name'] = name;
    map['age'] = age;
    return map;
  }

  static ValidIgnoreTest fromJson(Map<String, dynamic> map) {
    return ValidIgnoreTest(
      name: SafeCasteUtil.safeCast<String>(map['name']) ?? "",
      age: SafeCasteUtil.safeCast<int>(map['age']) ?? 0,
    );
  }
}

/// Helper class for chained copyWith operations
class _ValidIgnoreTestCopyWith {
  final ValidIgnoreTest _instance;
  const _ValidIgnoreTestCopyWith._(this._instance);

  /// Update name field
  _ValidIgnoreTestCopyWith name(String value) {
    return _ValidIgnoreTestCopyWith._(ValidIgnoreTest(
      name: value,
      nullablePassword: _instance.nullablePassword,
      passwordWithDefault: _instance.passwordWithDefault,
      age: _instance.age,
    ));
  }

  /// Update nullablePassword field
  _ValidIgnoreTestCopyWith nullablePassword(String? value) {
    return _ValidIgnoreTestCopyWith._(ValidIgnoreTest(
      name: _instance.name,
      nullablePassword: value,
      passwordWithDefault: _instance.passwordWithDefault,
      age: _instance.age,
    ));
  }

  /// Update passwordWithDefault field
  _ValidIgnoreTestCopyWith passwordWithDefault(String value) {
    return _ValidIgnoreTestCopyWith._(ValidIgnoreTest(
      name: _instance.name,
      nullablePassword: _instance.nullablePassword,
      passwordWithDefault: value,
      age: _instance.age,
    ));
  }

  /// Update age field
  _ValidIgnoreTestCopyWith age(int value) {
    return _ValidIgnoreTestCopyWith._(ValidIgnoreTest(
      name: _instance.name,
      nullablePassword: _instance.nullablePassword,
      passwordWithDefault: _instance.passwordWithDefault,
      age: value,
    ));
  }

  /// Build the final instance
  ValidIgnoreTest build() {
    return _instance;
  }

  /// Traditional copyWith method
  ValidIgnoreTest call({
    String? name,
    String? nullablePassword,
    String? passwordWithDefault,
    int? age,
  }) {
    return ValidIgnoreTest(
      name: name ?? _instance.name,
      nullablePassword: nullablePassword ?? _instance.nullablePassword,
      passwordWithDefault: passwordWithDefault ?? _instance.passwordWithDefault,
      age: age ?? _instance.age,
    );
  }
}
