name: dataforge_generator_example
description: Dataforge v1 build_runner example.
version: 1.0.0-dev.0
publish_to: none

environment:
  sdk: '>=3.9.0 <4.0.0'

dependencies:
  dataforge_annotation: 1.0.0-dev.0

dev_dependencies:
  build_runner: ^2.4.0
  dataforge:
    path: ../
  test: ^1.29.0
